"""Server-side workspace for uploads (Source Videos, assets) and renders.

Files live under ids generated by the server, never under client-supplied
paths. Each upload keeps its probe results next to the media so a restarted
server can still serve it.
"""

from __future__ import annotations

import pathlib
import secrets
import shutil
import string
import time

from yt.studio import models

_ID_BYTES = 8
_SOURCE_META = 'source.json'
_ASSET_META = 'asset.json'
_ANALYSIS_PROXY = 'analysis.mp4'
_RENDER_FILE = 'output.mp4'
_ALLOWED_SUFFIXES = ('.mp4', '.mov', '.m4v', '.mkv', '.webm')
_DEFAULT_SUFFIX = '.mp4'
_ASSET_SUFFIXES: dict[models.AssetKind, tuple[str, ...]] = {
    'image': ('.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp'),
    'audio': ('.mp3', '.m4a', '.aac', '.wav', '.ogg', '.opus', '.flac'),
}


class NotFoundError(LookupError):
  """Raised when an id does not name a stored item."""


def _is_valid_id(value: str) -> bool:
  return len(value) == _ID_BYTES * 2 and all(
      char in string.hexdigits for char in value
  )


class Workspace:
  """Owns the directories for uploads and renders."""

  def __init__(self, root: pathlib.Path, retention_hours: float) -> None:
    self._sources = root / 'sources'
    self._assets = root / 'assets'
    self._renders = root / 'renders'
    self._retention_sec = retention_hours * 3600

  def new_source(self, filename: str) -> tuple[str, pathlib.Path]:
    """Reserves a directory for an upload.

    Args:
      filename: The client file name (only its suffix is used).

    Returns:
      (source id, path to write the media to).
    """
    self.purge_expired()
    suffix = pathlib.PurePath(filename).suffix.lower()
    if suffix not in _ALLOWED_SUFFIXES:
      suffix = _DEFAULT_SUFFIX
    source_id = secrets.token_hex(_ID_BYTES)
    folder = self._sources / source_id
    folder.mkdir(parents=True)
    return source_id, folder / f'source{suffix}'

  def save_source(self, source: models.UploadedSource) -> None:
    """Stores the probe results of an upload."""
    folder = self._sources / source.source_id
    (folder / _SOURCE_META).write_text(
        source.model_dump_json(by_alias=True), encoding='utf-8'
    )

  def discard_source(self, source_id: str) -> None:
    """Deletes a failed or unwanted upload."""
    if _is_valid_id(source_id):
      shutil.rmtree(self._sources / source_id, ignore_errors=True)

  def load_source(
      self, source_id: str
  ) -> tuple[models.UploadedSource, pathlib.Path]:
    """Returns the upload record and its media path.

    Raises:
      NotFoundError: If the id is unknown or expired.
    """
    folder = self._sources / source_id
    meta = folder / _SOURCE_META
    if not _is_valid_id(source_id) or not meta.is_file():
      raise NotFoundError('업로드한 원본을 찾을 수 없습니다. 다시 업로드하세요.')
    source = models.UploadedSource.model_validate_json(
        meta.read_text(encoding='utf-8')
    )
    for suffix in _ALLOWED_SUFFIXES:
      media = folder / f'source{suffix}'
      if media.is_file():
        return source, media
    raise NotFoundError('업로드한 원본 파일이 없습니다. 다시 업로드하세요.')

  def analysis_proxy(self, source_id: str) -> pathlib.Path:
    """Returns where the Gemini analysis proxy of an upload is cached."""
    return self._sources / source_id / _ANALYSIS_PROXY

  def new_asset(
      self, kind: models.AssetKind, filename: str
  ) -> tuple[str, pathlib.Path]:
    """Reserves a directory for an image or audio upload.

    Args:
      kind: What the asset is used for.
      filename: The client file name (only its suffix is used).

    Returns:
      (asset id, path to write the file to).

    Raises:
      ValueError: If the suffix is not a supported file type for kind.
    """
    self.purge_expired()
    suffix = pathlib.PurePath(filename).suffix.lower()
    allowed = _ASSET_SUFFIXES[kind]
    if suffix not in allowed:
      raise ValueError(
          f'지원하지 않는 파일 형식입니다({suffix or "확장자 없음"}). '
          f'가능한 형식: {", ".join(allowed)}'
      )
    asset_id = secrets.token_hex(_ID_BYTES)
    folder = self._assets / asset_id
    folder.mkdir(parents=True)
    return asset_id, folder / f'asset{suffix}'

  def save_asset(self, asset: models.UploadedAsset) -> None:
    """Stores the probe results of an asset upload."""
    (self._assets / asset.asset_id / _ASSET_META).write_text(
        asset.model_dump_json(by_alias=True), encoding='utf-8'
    )

  def discard_asset(self, asset_id: str) -> None:
    """Deletes a failed asset upload."""
    if _is_valid_id(asset_id):
      shutil.rmtree(self._assets / asset_id, ignore_errors=True)

  def load_asset(
      self, asset_id: str
  ) -> tuple[models.UploadedAsset, pathlib.Path]:
    """Returns the asset record and its file path.

    Raises:
      NotFoundError: If the id is unknown or expired.
    """
    folder = self._assets / asset_id
    meta = folder / _ASSET_META
    if not _is_valid_id(asset_id) or not meta.is_file():
      raise NotFoundError(
          '추가한 이미지나 음악 파일을 찾을 수 없습니다. 다시 추가하세요.'
      )
    asset = models.UploadedAsset.model_validate_json(
        meta.read_text(encoding='utf-8')
    )
    for path in folder.iterdir():
      if path.name.startswith('asset.') and path.name != _ASSET_META:
        return asset, path
    raise NotFoundError('추가한 파일이 서버에 없습니다. 다시 추가하세요.')

  def new_render(self) -> tuple[str, pathlib.Path]:
    """Reserves a working directory for a render.

    Returns:
      (render id, directory where ffmpeg runs and writes output.mp4).
    """
    self.purge_expired()
    render_id = secrets.token_hex(_ID_BYTES)
    folder = self._renders / render_id
    folder.mkdir(parents=True)
    return render_id, folder

  @staticmethod
  def render_output(folder: pathlib.Path) -> pathlib.Path:
    """Returns the output path inside a render directory."""
    return folder / _RENDER_FILE

  def render_file(self, render_id: str) -> pathlib.Path:
    """Returns the rendered MP4 of an id.

    Raises:
      NotFoundError: If the id is unknown or expired.
    """
    path = self._renders / render_id / _RENDER_FILE
    if not _is_valid_id(render_id) or not path.is_file():
      raise NotFoundError('렌더 결과를 찾을 수 없습니다.')
    return path

  def purge_expired(self) -> None:
    """Deletes uploads and renders older than the retention period."""
    cutoff = time.time() - self._retention_sec
    for parent in (self._sources, self._assets, self._renders):
      if not parent.is_dir():
        continue
      for folder in parent.iterdir():
        if folder.is_dir() and folder.stat().st_mtime < cutoff:
          shutil.rmtree(folder, ignore_errors=True)
