"""Server-side workspace for uploads (Source Videos, assets) and renders.

Files live under ids generated by the server, never under client-supplied
paths. Each upload keeps its probe results next to the media so a restarted
server can still serve it.

With STUDIO_GCS_BUCKET set, the local directory is only a cache of a Cloud
Storage bucket: whatever is saved here is also uploaded under the same
relative name (sources/<id>/..., assets/<id>/..., renders/<id>/output.mp4)
and a local miss is served from the bucket, so several Cloud Run instances
and successive revisions share one Workspace. Without a bucket nothing
leaves the local disk, which is how local development runs.
"""

from __future__ import annotations

from collections.abc import Iterator
import mimetypes
import pathlib
import secrets
import shutil
import string
import threading
import time
from urllib import parse as urllib_parse

import google.auth
from google.auth import exceptions as google_auth_exceptions
from google.auth.transport import requests as google_auth_requests
import httpx

from src.core import models

_ID_BYTES = 8
_SOURCE_META = 'source.json'
_ASSET_META = 'asset.json'
_ANALYSIS_PROXY = 'analysis.mp4'
_TRANSCRIPT_FILE = 'transcript.json'
_VIDEO_CACHE_FILE = 'cache.json'
_YOUTUBE_CONTEXT_FILE = 'youtube.json'
_RENDER_FILE = 'output.mp4'
_ALLOWED_SUFFIXES = ('.mp4', '.mov', '.m4v', '.mkv', '.webm')
_DEFAULT_SUFFIX = '.mp4'
_ASSET_SUFFIXES: dict[models.AssetKind, tuple[str, ...]] = {
    'image': ('.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp'),
    'audio': ('.mp3', '.m4a', '.aac', '.wav', '.ogg', '.opus', '.flac'),
    'video': _ALLOWED_SUFFIXES,
}

_GCS_SCOPE = 'https://www.googleapis.com/auth/cloud-platform'
_GCS_API = 'https://storage.googleapis.com/storage/v1/b'
_GCS_UPLOAD_API = 'https://storage.googleapis.com/upload/storage/v1/b'
_CHUNK_BYTES = 16 * 1024 * 1024


class NotFoundError(LookupError):
  """Raised when an id does not name a stored item."""


class StorageError(RuntimeError):
  """Raised when the Cloud Storage bucket cannot be read or written."""


def _is_valid_id(value: str) -> bool:
  return len(value) == _ID_BYTES * 2 and all(
      char in string.hexdigits for char in value
  )


def _media_suffix(filename: str) -> str:
  suffix = pathlib.PurePath(filename).suffix.lower()
  return suffix if suffix in _ALLOWED_SUFFIXES else _DEFAULT_SUFFIX


class _Bucket:
  """A Cloud Storage bucket spoken to through its JSON API.

  google-auth provides the token and httpx the requests, so no further
  client library is needed. Calls block and may run from several threads.
  """

  def __init__(self, name: str) -> None:
    self._name = name
    try:
      self._credentials, _ = google.auth.default(scopes=[_GCS_SCOPE])
    except google_auth_exceptions.GoogleAuthError as exc:
      raise StorageError(
          f'STUDIO_GCS_BUCKET={name}이(가) 설정되었지만 Google Cloud 인증 '
          f'정보를 찾지 못했습니다: {exc}'
      ) from exc
    self._lock = threading.Lock()
    self._http = httpx.Client(timeout=httpx.Timeout(300.0, connect=30.0))

  @property
  def name(self) -> str:
    return self._name

  def _headers(self) -> dict[str, str]:
    with self._lock:
      if not self._credentials.valid:
        self._credentials.refresh(google_auth_requests.Request())
      return {'Authorization': f'Bearer {self._credentials.token}'}

  def _object_url(self, name: str) -> str:
    quoted = urllib_parse.quote(name, safe='')
    return f'{_GCS_API}/{self._name}/o/{quoted}'

  def create_resumable_upload(
      self,
      name: str,
      content_type: str,
      size_bytes: int,
      origin: str = '',
  ) -> str:
    """Starts a GCS resumable upload session and returns its session URL."""
    headers = {
        **self._headers(),
        'X-Upload-Content-Type': content_type or 'video/mp4',
        'X-Upload-Content-Length': str(size_bytes),
    }
    if origin:
      headers['Origin'] = origin
    try:
      response = self._http.post(
          f'{_GCS_UPLOAD_API}/{self._name}/o',
          params={'uploadType': 'resumable', 'name': name},
          headers=headers,
      )
      response.raise_for_status()
      location = response.headers.get('Location', '').strip()
      if not location:
        raise StorageError('GCS 업로드 세션 URL을 받지 못했습니다.')
      return location
    except (httpx.HTTPError, google_auth_exceptions.GoogleAuthError) as exc:
      raise StorageError(
          f'gs://{self._name}/{name} 업로드 세션 생성에 실패했습니다: {exc}'
      ) from exc

  def stat_size(self, name: str) -> int | None:
    """Returns the byte size of an object in the bucket, or None if missing."""
    try:
      response = self._http.get(
          self._object_url(name),
          params={'fields': 'size'},
          headers=self._headers(),
      )
      if response.status_code == 404:
        return None
      response.raise_for_status()
      data = response.json()
      return int(data.get('size', 0))
    except (httpx.HTTPError, google_auth_exceptions.GoogleAuthError) as exc:
      raise StorageError(
          f'gs://{self._name}/{name} 메타데이터 조회에 실패했습니다: {exc}'
      ) from exc

  def upload(self, name: str, path: pathlib.Path) -> None:
    """Uploads a local file as an object, replacing any earlier one."""
    size = path.stat().st_size
    content_type = (
        mimetypes.guess_type(path.name)[0] or 'application/octet-stream'
    )

    def chunks() -> Iterator[bytes]:
      with path.open('rb') as handle:
        while block := handle.read(_CHUNK_BYTES):
          yield block

    try:
      response = self._http.post(
          f'{_GCS_UPLOAD_API}/{self._name}/o',
          params={'uploadType': 'media', 'name': name},
          headers={
              **self._headers(),
              'Content-Type': content_type,
              'Content-Length': str(size),
          },
          content=chunks(),
      )
      response.raise_for_status()
    except (httpx.HTTPError, google_auth_exceptions.GoogleAuthError) as exc:
      raise StorageError(
          f'gs://{self._name}/{name} 업로드에 실패했습니다: {exc}'
      ) from exc

  def download(self, name: str, path: pathlib.Path) -> bool:
    """Downloads an object to path; False when the object does not exist.

    The file appears under its final name only once it is complete.
    """
    partial = path.with_name(path.name + '.part')
    try:
      with self._http.stream(
          'GET',
          self._object_url(name),
          params={'alt': 'media'},
          headers=self._headers(),
      ) as response:
        if response.status_code == 404:
          return False
        response.raise_for_status()
        path.parent.mkdir(parents=True, exist_ok=True)
        with partial.open('wb') as handle:
          for block in response.iter_bytes(_CHUNK_BYTES):
            handle.write(block)
      partial.replace(path)
      return True
    except (httpx.HTTPError, google_auth_exceptions.GoogleAuthError) as exc:
      partial.unlink(missing_ok=True)
      raise StorageError(
          f'gs://{self._name}/{name} 다운로드에 실패했습니다: {exc}'
      ) from exc

  def delete_prefix(self, prefix: str) -> None:
    """Deletes every object whose name starts with prefix."""
    try:
      for name in self._list(prefix):
        response = self._http.delete(
            self._object_url(name), headers=self._headers()
        )
        if response.status_code != 404:
          response.raise_for_status()
    except (httpx.HTTPError, google_auth_exceptions.GoogleAuthError) as exc:
      raise StorageError(
          f'gs://{self._name}/{prefix} 삭제에 실패했습니다: {exc}'
      ) from exc

  def _list(self, prefix: str) -> list[str]:
    names: list[str] = []
    page_token = ''
    while True:
      params = {'prefix': prefix, 'fields': 'items/name,nextPageToken'}
      if page_token:
        params['pageToken'] = page_token
      response = self._http.get(
          f'{_GCS_API}/{self._name}/o',
          params=params,
          headers=self._headers(),
      )
      response.raise_for_status()
      data = response.json()
      names.extend(item['name'] for item in data.get('items', []))
      page_token = data.get('nextPageToken', '')
      if not page_token:
        return names


class Workspace:
  """Owns the directories for uploads and renders, and their bucket copies.

  Every method blocks (disk and, with a bucket, network I/O); async callers
  run them in a thread.
  """

  def __init__(
      self, root: pathlib.Path, retention_hours: float, gcs_bucket: str = ''
  ) -> None:
    """Opens the Workspace.

    Args:
      root: The local directory (created on demand).
      retention_hours: How long local uploads and renders are kept.
      gcs_bucket: Name of the Cloud Storage bucket to mirror into; '' keeps
        every file local only.

    Raises:
      StorageError: If a bucket is named but no credentials are found.
    """
    self._root = root
    self._sources = root / 'sources'
    self._assets = root / 'assets'
    self._renders = root / 'renders'
    self._sessions = root / 'sessions'
    self._retention_sec = retention_hours * 3600
    self._bucket = _Bucket(gcs_bucket) if gcs_bucket else None

  @property
  def bucket_name(self) -> str:
    """The Cloud Storage bucket behind this Workspace, or ''."""
    return self._bucket.name if self._bucket is not None else ''

  # -- bucket plumbing ------------------------------------------------------

  def _object_name(self, path: pathlib.Path) -> str:
    return path.relative_to(self._root).as_posix()

  def _store(self, path: pathlib.Path) -> None:
    """Copies a local file to the bucket (nothing to do without one)."""
    if self._bucket is not None:
      self._bucket.upload(self._object_name(path), path)

  def _ensure_local(self, path: pathlib.Path) -> bool:
    """Returns whether path exists, fetching it from the bucket if needed."""
    if path.is_file():
      return True
    if self._bucket is None:
      return False
    return self._bucket.download(self._object_name(path), path)

  def _remove(self, folder: pathlib.Path) -> None:
    shutil.rmtree(folder, ignore_errors=True)
    if self._bucket is not None:
      self._bucket.delete_prefix(self._object_name(folder) + '/')

  def _write_json(self, path: pathlib.Path, model: models.StudioModel) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(model.model_dump_json(by_alias=True), encoding='utf-8')
    self._store(path)

  def _read_json(self, path: pathlib.Path) -> str | None:
    if not self._ensure_local(path):
      return None
    return path.read_text(encoding='utf-8')

  # -- Source Videos --------------------------------------------------------

  def new_source(self, filename: str) -> tuple[str, pathlib.Path]:
    """Reserves a directory for an upload.

    Args:
      filename: The client file name (only its suffix is used).

    Returns:
      (source id, path to write the media to).
    """
    source_id = secrets.token_hex(_ID_BYTES)
    folder = self._sources / source_id
    folder.mkdir(parents=True)
    return source_id, folder / f'source{_media_suffix(filename)}'

  def init_source_upload(
      self,
      filename: str,
      size_bytes: int,
      content_type: str,
      origin: str = '',
  ) -> tuple[str, str] | None:
    """Starts a direct GCS resumable upload session for a Source Video.

    Args:
      filename: Client file name (only its suffix is used).
      size_bytes: Total byte length of the upload.
      content_type: MIME type of the video file.
      origin: Request Origin header so GCS enables CORS on the session URL.

    Returns:
      (source_id, resumable_upload_url), or None when no bucket is configured.
    """
    if self._bucket is None:
      return None
    source_id, media = self.new_source(filename)
    upload_url = self._bucket.create_resumable_upload(
        self._object_name(media),
        content_type,
        size_bytes,
        origin=origin,
    )
    return source_id, upload_url

  def verify_source_object(self, source_id: str, filename: str) -> int | None:
    """Returns the byte size of an uploaded source media, or None if missing."""
    if not _is_valid_id(source_id):
      return None
    media = self._sources / source_id / f'source{_media_suffix(filename)}'
    if media.is_file():
      return media.stat().st_size
    if self._bucket is None:
      return None
    return self._bucket.stat_size(self._object_name(media))

  def save_source_meta(self, source: models.UploadedSource) -> None:
    """Stores only the source.json record without re-uploading the media."""
    folder = self._sources / source.source_id
    self._write_json(folder / _SOURCE_META, source)

  def save_source(self, source: models.UploadedSource) -> None:
    """Stores the probe results of an upload (and mirrors the media).

    The media goes to the bucket before its record, so a record found
    there always has its media.
    """
    folder = self._sources / source.source_id
    self._store(folder / f'source{_media_suffix(source.filename)}')
    self.save_source_meta(source)

  def discard_source(self, source_id: str) -> None:
    """Deletes a failed or unwanted upload."""
    if _is_valid_id(source_id):
      self._remove(self._sources / source_id)

  def load_source(
      self, source_id: str
  ) -> tuple[models.UploadedSource, pathlib.Path]:
    """Returns the upload record and its media path.

    Raises:
      NotFoundError: If the id is unknown or expired.
    """
    folder = self._sources / source_id
    raw = self._read_json(folder / _SOURCE_META) if _is_valid_id(
        source_id
    ) else None
    if raw is None:
      raise NotFoundError('업로드한 원본을 찾을 수 없습니다. 다시 업로드하세요.')
    source = models.UploadedSource.model_validate_json(raw)
    media = folder / f'source{_media_suffix(source.filename)}'
    if self._ensure_local(media):
      return source, media
    for suffix in _ALLOWED_SUFFIXES:
      if (folder / f'source{suffix}').is_file():
        return source, folder / f'source{suffix}'
    raise NotFoundError('업로드한 원본 파일이 없습니다. 다시 업로드하세요.')

  def analysis_proxy(self, source_id: str) -> pathlib.Path:
    """Returns where the Gemini analysis proxy of an upload is written."""
    return self._sources / source_id / _ANALYSIS_PROXY

  def load_analysis_proxy(self, source_id: str) -> pathlib.Path | None:
    """Returns the analysis proxy made earlier, or None when there is none."""
    path = self.analysis_proxy(source_id)
    if _is_valid_id(source_id) and self._ensure_local(path):
      return path
    return None

  def save_analysis_proxy(self, source_id: str) -> None:
    """Mirrors a freshly made analysis proxy."""
    self._store(self.analysis_proxy(source_id))

  def load_transcript(self, source_id: str) -> models.StoredTranscript | None:
    """Returns the full transcript of an upload, or None before analysis."""
    if not _is_valid_id(source_id):
      return None
    raw = self._read_json(self._sources / source_id / _TRANSCRIPT_FILE)
    if raw is None:
      return None
    return models.StoredTranscript.model_validate_json(raw)

  def save_transcript(
      self, source_id: str, transcript: models.StoredTranscript
  ) -> None:
    """Stores the full transcript extracted by the first analysis."""
    self._write_json(self._sources / source_id / _TRANSCRIPT_FILE, transcript)

  def load_video_cache(self, source_id: str) -> models.CachedVideoMeta | None:
    """Returns the Context Cache record of an upload, or None."""
    if not _is_valid_id(source_id):
      return None
    raw = self._read_json(self._sources / source_id / _VIDEO_CACHE_FILE)
    if raw is None:
      return None
    return models.CachedVideoMeta.model_validate_json(raw)

  def save_video_cache(
      self, source_id: str, cache: models.CachedVideoMeta
  ) -> None:
    """Stores the Context Cache record of an upload's analysis proxy."""
    self._write_json(self._sources / source_id / _VIDEO_CACHE_FILE, cache)

  def discard_video_cache(self, source_id: str) -> None:
    """Forgets an expired or unusable Context Cache record."""
    path = self._sources / source_id / _VIDEO_CACHE_FILE
    path.unlink(missing_ok=True)
    if self._bucket is not None:
      self._bucket.delete_prefix(self._object_name(path))

  def load_youtube_context(
      self, source_id: str
  ) -> models.YouTubeVideoContext | None:
    """Returns the linked YouTube video context of an upload, or None."""
    if not _is_valid_id(source_id):
      return None
    raw = self._read_json(self._sources / source_id / _YOUTUBE_CONTEXT_FILE)
    if raw is None:
      return None
    return models.YouTubeVideoContext.model_validate_json(raw)

  def save_youtube_context(
      self, source_id: str, context: models.YouTubeVideoContext
  ) -> None:
    """Stores the linked YouTube video context (retention + captions)."""
    self._write_json(
        self._sources / source_id / _YOUTUBE_CONTEXT_FILE, context
    )

  # -- OAuth Sessions -------------------------------------------------------

  def new_session_id(self) -> str:
    """Generates a fresh session identifier."""
    self.purge_expired()
    return secrets.token_hex(_ID_BYTES)

  def save_session(self, session: models.OAuthSession) -> None:
    """Stores an OAuth session (and mirrors it to the bucket)."""
    folder = self._sessions / session.session_id
    self._write_json(folder / 'session.json', session)

  def load_session(self, session_id: str) -> models.OAuthSession | None:
    """Returns the OAuth session for session_id, or None when unknown."""
    if not _is_valid_id(session_id):
      return None
    raw = self._read_json(self._sessions / session_id / 'session.json')
    if raw is None:
      return None
    return models.OAuthSession.model_validate_json(raw)

  def discard_session(self, session_id: str) -> None:
    """Deletes an OAuth session."""
    if _is_valid_id(session_id):
      self._remove(self._sessions / session_id)

  # -- Assets ---------------------------------------------------------------

  def new_asset(
      self, kind: models.AssetKind, filename: str
  ) -> tuple[str, pathlib.Path]:
    """Reserves a directory for an image or audio upload.

    Args:
      kind: What the asset is used for.
      filename: The client file name (only its suffix is used).

    Returns:
      (asset id, path to write the file to).

    Raises:
      ValueError: If the suffix is not a supported file type for kind.
    """
    self.purge_expired()
    suffix = pathlib.PurePath(filename).suffix.lower()
    allowed = _ASSET_SUFFIXES[kind]
    if suffix not in allowed:
      raise ValueError(
          f'지원하지 않는 파일 형식입니다({suffix or "확장자 없음"}). '
          f'가능한 형식: {", ".join(allowed)}'
      )
    asset_id = secrets.token_hex(_ID_BYTES)
    folder = self._assets / asset_id
    folder.mkdir(parents=True)
    return asset_id, folder / f'asset{suffix}'

  def save_asset(self, asset: models.UploadedAsset) -> None:
    """Stores the probe results of an asset upload (and mirrors the file)."""
    folder = self._assets / asset.asset_id
    suffix = pathlib.PurePath(asset.filename).suffix.lower()
    self._store(folder / f'asset{suffix}')
    self._write_json(folder / _ASSET_META, asset)

  def discard_asset(self, asset_id: str) -> None:
    """Deletes a failed asset upload."""
    if _is_valid_id(asset_id):
      self._remove(self._assets / asset_id)

  def load_asset(
      self, asset_id: str
  ) -> tuple[models.UploadedAsset, pathlib.Path]:
    """Returns the asset record and its file path.

    Raises:
      NotFoundError: If the id is unknown or expired.
    """
    folder = self._assets / asset_id
    raw = self._read_json(folder / _ASSET_META) if _is_valid_id(
        asset_id
    ) else None
    if raw is None:
      raise NotFoundError(
          '추가한 이미지나 음악 파일을 찾을 수 없습니다. 다시 추가하세요.'
      )
    asset = models.UploadedAsset.model_validate_json(raw)
    suffix = pathlib.PurePath(asset.filename).suffix.lower()
    path = folder / f'asset{suffix}'
    if self._ensure_local(path):
      return asset, path
    for candidate in folder.iterdir():
      if candidate.name.startswith('asset.') and candidate.name != _ASSET_META:
        return asset, candidate
    raise NotFoundError('추가한 파일이 서버에 없습니다. 다시 추가하세요.')

  # -- Renders --------------------------------------------------------------

  def new_render(self) -> tuple[str, pathlib.Path]:
    """Reserves a working directory for a render.

    Returns:
      (render id, path of output.mp4 inside the directory where ffmpeg runs).
    """
    self.purge_expired()
    render_id = secrets.token_hex(_ID_BYTES)
    folder = self._renders / render_id
    folder.mkdir(parents=True)
    return render_id, folder / _RENDER_FILE

  def save_render(self, render_id: str) -> None:
    """Mirrors a finished render so any instance can serve it."""
    self._store(self._renders / render_id / _RENDER_FILE)

  def render_file(self, render_id: str) -> pathlib.Path:
    """Returns the rendered MP4 of an id.

    Raises:
      NotFoundError: If the id is unknown or expired.
    """
    path = self._renders / render_id / _RENDER_FILE
    if not _is_valid_id(render_id) or not self._ensure_local(path):
      raise NotFoundError('렌더 결과를 찾을 수 없습니다.')
    return path

  def purge_expired(self) -> None:
    """Deletes local uploads and renders older than the retention period.

    Bucket objects are not touched here; the bucket's own lifecycle rule
    (see terraform/storage.tf) expires them.
    """
    cutoff = time.time() - self._retention_sec
    for parent in (
        self._sources,
        self._assets,
        self._renders,
        self._sessions,
    ):
      if not parent.is_dir():
        continue
      for folder in parent.iterdir():
        if folder.is_dir() and folder.stat().st_mtime < cutoff:
          shutil.rmtree(folder, ignore_errors=True)
